apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: website-mem-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: website-deployment
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
